gettakaro/takaro

.husky/pre-commit
.lintstagedrc.json
package-lock.json
package.json

Only lint staged files on commit.

chore: lint-staged

---

scripts/dev-init.sh

Oh yes I'm using GitMoji now 😜

🔨: fix script to work on Unix systems

---

package-lock.json
package.json
packages/web-docs/package.json

Docusaurus does not support react 18

Fix: override docusaurus to use react 17

---

packages/lib-components/src/components/feedback/Alert/index.tsx
packages/lib-components/src/components/feedback/Alert/style.ts
packages/lib-components/src/components/feedback/NotificationBanner/index.tsx
packages/lib-components/src/components/feedback/Tooltip/index.tsx
packages/lib-components/src/components/feedback/snacks/CookieConsent/style.ts
packages/lib-components/src/components/feedback/snacks/Drawer/index.tsx
packages/lib-components/src/components/feedback/snacks/NetworkDetector/index.tsx
packages/lib-components/src/components/inputs/Button/style.ts
packages/lib-components/src/components/inputs/IconButton/index.tsx
packages/lib-components/src/components/inputs/IconButton/style.ts
packages/lib-components/src/components/inputs/Select/Option.tsx
packages/lib-components/src/components/inputs/Select/style.ts
packages/lib-components/src/components/inputs/Switch/style.ts
packages/lib-components/src/components/other/ActionMenu/index.tsx
packages/lib-components/src/components/other/ActionMenu/style.ts
packages/lib-components/src/components/visual/Card/Card.stories.tsx
packages/lib-components/src/components/visual/Card/index.tsx
packages/lib-components/src/hooks/useModal.tsx
packages/lib-components/src/modals/ConfirmationModal/index.tsx
packages/lib-components/src/stories/Elevation.mdx
packages/lib-components/src/stories/Elevation.stories.mdx
packages/lib-components/src/styled/Snackbar.tsx
packages/lib-components/src/styled/elevation.ts
packages/lib-components/src/styled/index.ts
packages/lib-components/src/styled/theme.ts

Elevation is one of the parts of the Takaro design system. It basically sets different elevation levels for different components that need higher or lower visual attention. Most elevated components have great default elevation levels, but can be tweaked individually.

Feat: Design system elevation

---

scripts/dev-vm.sh

Refactor the dev script for starting the firecracker process & configuring the microvm

chore: refactor dev script

---

package-lock.json
packages/lib-components/package.json

fix: move yup out of pkg dependency list

---

package-lock.json
packages/lib-components/package.json
packages/lib-components/src/components/actions/DropdownButton/index.tsx
packages/lib-components/src/components/actions/SupportButton/index.tsx
packages/lib-components/src/components/other/ActionMenu/ActionMenu.stories.tsx

@floating-ui/react contains everything that @floating-ui/react-dom contains and more. The react-dom version is in case you don't need more than position stuff, but we do...

Remove @floating-ui/react-dom dep

---

packages/app-api/src/db/hook.ts
packages/app-api/src/service/CommandService.ts
packages/app-api/src/service/GameServerService.ts
packages/app-api/src/service/HookService.ts
packages/lib-db/src/migrations/sql/20230407173055-hook-regex-optional.ts
packages/lib-modules/src/main.ts
packages/lib-modules/src/modules/playerGreeter/hooks/playerConnected.js
packages/lib-modules/src/modules/playerGreeter/index.ts

This is really simple, mostly a PoC to integrate hooks with config :)

feat: add playerGreeter module

---

packages/web-main/src/Router.tsx

Temporarily disable lazy routing until this is fixed

fix(Router): temp disable lazy loading for gameserver dashboard

---

packages/app-api/src/lib/DiscordBot.ts
packages/app-api/src/lib/systemConfig.ts
packages/app-api/src/service/DiscordService.ts
packages/lib-modules/src/dto.ts
packages/lib-modules/src/modules/chatBridge/hooks/DiscordToGame.js
packages/lib-modules/src/modules/chatBridge/hooks/PlayerConnected.js
packages/lib-modules/src/modules/chatBridge/hooks/PlayerDisconnected.js
packages/lib-modules/src/modules/chatBridge/index.ts

- Fix dupe messages
- Player connected and disconnected messages

feat: extend chat bridge

---

packages/lib-components/src/components/feedback/Popover/Popover.stories.tsx
packages/lib-components/src/components/feedback/Popover/PopoverContent.tsx
packages/lib-components/src/components/feedback/Popover/PopoverContext.tsx
packages/lib-components/src/components/feedback/Popover/PopoverTrigger.tsx
packages/lib-components/src/components/feedback/Popover/index.tsx
packages/lib-components/src/components/feedback/Popover/usePopover.tsx
packages/lib-components/src/components/feedback/index.ts
packages/lib-components/src/components/inputs/layout/Description.tsx
packages/lib-components/src/styled/GlobalStyle.ts
packages/web-main/src/App.tsx
packages/web-main/src/components/studio/Header.tsx
packages/web-main/src/pages/studio/index.tsx

fyi: popover may seem similar to tooltip. Popover is used when the user interacts with the popup. Tooltip just shows a text message.

Feat: <Popover />

---

packages/app-api/src/lib/systemConfig.ts
packages/app-api/src/service/CommandService.ts
packages/app-api/src/service/GameServerService.ts
packages/app-api/src/service/__tests__/CommandService.integration.test.ts
packages/test/src/__snapshots__/GameServerController/Get list of installed modules.json
packages/test/src/__snapshots__/Module Assignments/Install a built-in module.json
packages/test/src/__snapshots__/Module Assignments/Update installation config.json

feat; allow teleports to be delayed

---

packages/app-api/src/controllers/__tests__/ModuleAssignments.integration.test.ts
packages/lib-modules/src/__tests__/help.integration.test.ts
packages/lib-modules/src/__tests__/teleports.integration.test.ts
packages/lib-modules/src/modules/teleports/commands/setprivate.js
packages/lib-modules/src/modules/teleports/commands/setpublic.js
packages/lib-modules/src/modules/teleports/commands/teleport.js
packages/lib-modules/src/modules/teleports/commands/tplist.js
packages/lib-modules/src/modules/teleports/index.ts
packages/test/src/__snapshots__/Module Assignments/Update installation config.json

feat: implement public/private teleports

---

packages/app-api/src/main.ts
packages/app-connector/src/main.ts
packages/app-mock-gameserver/src/main.ts
packages/app-vmm/src/main.ts

fix: make config validation a bit more robust

---

packages/web-main/src/Router.tsx
packages/web-main/src/frames/StudioFrame.tsx
packages/web-main/src/paths.ts

fix: redirect when module not found in Studio

---

.github/workflows/builds.yml
.github/workflows/deploy-docs.yml
.github/workflows/docker.yml

This reverts commit 2249e327e50271d8af5fa98d93105cdfc0e79576.

Revert "ci: no retries"

---

packages/app-api/src/controllers/DiscordController.ts
packages/app-api/src/controllers/GameServerController.ts
packages/lib-apiclient/src/generated/api.ts
packages/lib-apiclient/src/generated/common.ts
packages/lib-components/src/components/inputs/Switch/style.ts
packages/lib-components/src/styled/GlobalStyle.ts
packages/lib-gameserver/src/gameservers/7d2d/index.ts
packages/lib-gameserver/src/gameservers/mock/index.ts
packages/lib-gameserver/src/gameservers/rust/index.ts
packages/lib-gameserver/src/interfaces/GameServer.ts
packages/web-main/src/components/DiscordSettings/ServerCard.tsx
packages/web-main/src/queries/discord/queries.tsx
packages/web-main/src/queries/gameservers/queries.tsx

Fix: some API types

---

.github/workflows/docker.yml
scripts/dev-data.mjs

This is a hopeful fix to help with #303 where we have temporary failures pushing images to GHCR

ci: pin buildkit version

---

docker-compose.yml
packages/lib-modules/src/modules/teleports/commands/deletetp.js
packages/lib-modules/src/modules/teleports/commands/setprivate.js
packages/lib-modules/src/modules/teleports/commands/setpublic.js
packages/lib-modules/src/modules/teleports/commands/settp.js
packages/lib-modules/src/modules/teleports/commands/teleport.js
packages/lib-modules/src/modules/teleports/commands/tplist.js

also made teleport variables module scoped & respond back to player via PM

fix: tplist broken when player has used teleports

---

packages/app-api/src/db/player.ts
packages/app-api/src/db/playerOnGameserver.ts
packages/app-api/src/service/GameServerService.ts
packages/app-api/src/service/PlayerOnGameserverService.ts
packages/app-api/src/service/PlayerService.ts
packages/app-api/src/workers/__tests__/eventWorker.integration.test.ts
packages/lib-apiclient/src/generated/api.ts
packages/test/src/integrationTest.ts

PlayerOnGameServer entries were not being created properly

fix: an issue when the same player logs into multiple gameservers

---

.vscode/launch.json
docker-compose.yml
package-lock.json
package.json
packages/app-api/src/service/DomainService.ts
packages/app-vmm/package.json
packages/app-vmm/src/config.ts
packages/app-vmm/src/service/workers/executeFunction.ts
packages/lib-aws/package.json
packages/lib-aws/src/config.ts
packages/lib-aws/src/createLambda.ts
packages/lib-aws/src/deleteLambda.ts
packages/lib-aws/src/executeLambda.ts
packages/lib-aws/src/main.ts
packages/lib-aws/tsconfig.build.json
packages/lib-aws/tsconfig.json
scripts/dev-data.mjs
scripts/dev-init.sh
scripts/dev-vm.sh

Co-authored-by: Emiel Van Severen <emielvanseveren@users.noreply.github.com>
Co-authored-by: Branco Bruyneel <brancobruyneel@users.noreply.github.com>

Lambda integration

---

.github/workflows/docker.yml

lib-modules tests are still a little too brittle :(

ci: re-add retry for node ci

---

packages/lib-components/src/components/inputs/CodeField/index.tsx
packages/lib-components/src/components/inputs/EditableField/index.tsx
packages/lib-components/src/components/inputs/TagField/Generic.tsx
packages/lib-components/src/components/inputs/TextAreaField/Generic.tsx
packages/lib-components/src/components/inputs/TextField/Generic.tsx

which we don't want, we have our own validation

Fix: required on input fields triggers builtin html validation

---

packages/app-api/src/db/command.ts
packages/app-api/src/lib/systemConfig.ts
packages/lib-db/src/migrations/sql/20231124140441-json-module-assignments.ts
packages/lib-modules/src/__tests__/aliases.integration.test.ts

feat: aliases for commands

---

packages/app-api/src/db/playerOnGameserver.ts
packages/app-api/src/lib/__tests__/commandParser.unit.test.ts
packages/app-api/src/lib/commandParser.ts
packages/app-api/src/lib/tryResolvePlayer.ts
packages/app-api/src/service/CommandService.ts
packages/app-api/src/service/PlayerOnGameserverService.ts
packages/lib-modules/src/__tests__/commandArgs.integration.test.ts
packages/lib-queues/src/dataDefinitions.ts
packages/web-main/src/components/modules/Editor/configs/commandConfig.tsx

feat: add support for player arg type

---

packages/app-api/src/controllers/PlayerOnGameserverController.ts
packages/app-api/src/controllers/__tests__/PlayerOnGameserverController.integration.test.ts
packages/app-api/src/db/playerOnGameserver.ts
packages/app-api/src/executors/executeFunction.ts
packages/app-api/src/executors/executeLocal.ts
packages/app-api/src/lib/systemConfig.ts
packages/app-api/src/service/PlayerOnGameserverService.ts
packages/lib-apiclient/src/generated/api.ts
packages/lib-function-helpers/src/TakaroUserError.ts
packages/lib-function-helpers/src/main.ts
packages/lib-modules/src/__tests__/systemConfigCost.integration.test.ts
packages/lib-modules/src/modules/gimme/commands/gimme.js
packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
packages/lib-modules/src/modules/teleports/commands/deletetp.js
packages/lib-modules/src/modules/teleports/commands/setprivate.js
packages/lib-modules/src/modules/teleports/commands/setpublic.js
packages/lib-modules/src/modules/teleports/commands/settp.js
packages/lib-modules/src/modules/teleports/commands/teleport.js
packages/lib-modules/src/modules/utils/commands/help.js
packages/test/src/__snapshots__/GameServerController/Get list of installed modules.json
packages/test/src/__snapshots__/Module Assignments/Install a built-in module.json
packages/test/src/__snapshots__/Module Assignments/Update installation config.json
packages/test/src/test/waitForEvents.ts

feat: add system config for command cost

---

packages/web-docs/pages/advanced/modules.md

docs: command arguments

---

packages/app-api/src/middlewares/onlyIfEconomyEnabled.ts
packages/app-api/src/service/EventService.ts
packages/app-api/src/service/PlayerOnGameserverService.ts
packages/lib-apiclient/src/generated/api.ts
packages/web-main/src/components/events/EventFeed/EventItem.tsx
packages/web-main/src/pages/events/index.tsx

feat: add events for economy changes

---

packages/lib-components/src/components/actions/Button/style.ts
packages/lib-components/src/components/feedback/ErrorPage/index.tsx
packages/lib-components/src/components/inputs/RadioGroup/Radio/style.ts
packages/lib-components/src/components/inputs/layout/Label/style.ts
packages/lib-components/src/components/other/Empty/index.tsx
packages/lib-components/src/components/visual/Divider/index.tsx
packages/lib-components/src/styled/theme.ts
packages/web-docs/pages/development/common-tasks/resetting-data.md
packages/web-docs/pages/development/common-tasks/running-tests.mdx
packages/web-docs/pages/development/database.mdx
packages/web-docs/pages/development/getting-started.md
packages/web-main/src/App.tsx
scripts/dev-reset-data.sh

⚠️ Branch not based upon main: silly goose 🪿

Fix styling gray key

---

packages/app-api/src/service/GameServerService.ts
packages/app-connector/src/lib/GameServerManager.ts
packages/app-connector/src/lib/worker.ts
packages/lib-apiclient/src/generated/api.ts
packages/lib-modules/src/dto/takaroEvents.ts
packages/web-main/src/components/events/EventFeed/EventItem.tsx
packages/web-main/src/pages/events/index.tsx

Also prevents connector from continuously connecting to servers that are misconfigured

feat: basic server status event

---

packages/app-api/src/controllers/__tests__/ModuleController.integration.test.ts
packages/test/src/__snapshots__/ModuleController/Does not allow creating modules with builtin parameter set.json

fix: rename a file that has quotes in it

---

packages/app-api/src/service/StatsService.ts
packages/web-main/src/queries/stats.tsx
packages/web-main/src/routes/_auth/_global/dashboard.tsx

feat: replace old metric and add daily active players metric

---

packages/lib-components/src/components/inputs/CheckBox/Controlled.tsx
packages/lib-components/src/components/inputs/CheckBox/Generic.tsx
packages/lib-components/src/components/inputs/CheckBox/style.ts
packages/lib-components/src/components/inputs/InputProps.ts
packages/lib-components/src/components/inputs/RadioGroup/Controlled.tsx
packages/lib-components/src/components/inputs/Switch/Generic.tsx
packages/lib-components/src/components/inputs/Switch/style.ts
packages/lib-components/src/components/inputs/layout/InputWrapper.ts
packages/lib-components/src/components/inputs/selects/SelectField/Controlled.tsx
packages/lib-components/src/styled/GlobalStyle.ts
packages/web-main/src/components/selects/ItemSelectQuery/ItemSelectQuery.stories.tsx
packages/web-main/src/components/selects/ItemSelectQuery/index.tsx
packages/web-main/src/components/selects/PlayerSelectQuery.tsx
packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/ShopListingBuyForm.tsx

and get rid of half implemented hasmargin

Refactor: use pure css switch and checkbox

---

packages/app-api/src/db/domain.ts
packages/app-api/src/service/DomainService.ts
packages/lib-apiclient/src/generated/api.ts
packages/lib-db/src/migrations/sql/20240814133931-domain-ext-ref.ts

This helps with the stripe integration and keeping name pretty displayable

feat: add ability to set external references for domains

---

.github/workflows/docker.yml

Run CI on Github again

---

packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
packages/test/src/__snapshots__/UserController/Inviting a user that already exists in a different domain should work transparently.json
packages/test/src/__snapshots__/UserController/Inviting a user that is already invited should return the existing user.json

This issue was already resolved when we implemented player linking. This commit just adds some tests to avoid regressions in the future

Handle inviting users that already exist better

---

scripts/setup-data-folders.sh

I noticed that after rebuilding/restarting the permissions needed to be fixed again... Quick improvement :)

fix: _data permissions issue

---

packages/lib-components/src/helpers/getInitials.ts
packages/lib-db/src/migrations/sql/20240929143849-player-name-null.ts

IDs are enough to identify anyways

Allow player name to be null

---

packages/lib-components/src/components/feedback/ErrorPage/index.tsx
packages/web-docs/docs/advanced/api.md

changed old url to new domain takaro.io

Fix broken links in docs

---

packages/lib-components/src/components/data/Table/subcomponents/Filter/field.tsx
packages/lib-components/src/components/data/Table/subcomponents/Pagination/PageSizeSelect.tsx
packages/lib-components/src/components/inputs/Date/DateRangePicker/QuickSelect/index.tsx
packages/lib-components/src/components/inputs/Date/subcomponents/RelativePicker/index.tsx
packages/lib-components/src/components/inputs/DurationField/Generic.tsx
packages/lib-components/src/components/inputs/selects/SelectField/Controlled.tsx
packages/lib-components/src/components/inputs/selects/SelectField/Generic/index.tsx
packages/lib-components/src/components/inputs/selects/SelectQueryField/Controlled.tsx
packages/lib-components/src/components/inputs/selects/SelectQueryField/Generic/index.tsx
packages/web-main/src/components/JsonSchemaForm/widgets/ItemWidget.tsx
packages/web-main/src/components/JsonSchemaForm/widgets/SelectWidget.tsx
packages/web-main/src/components/selects/CountrySelectField/index.tsx
packages/web-main/src/components/selects/EventNameSelectField/index.tsx
packages/web-main/src/components/selects/GameServerSelectQueryField/index.tsx
packages/web-main/src/components/selects/ItemSelectQueryField/index.tsx
packages/web-main/src/components/selects/ModuleSelectQueryField.tsx
packages/web-main/src/components/selects/PlayerSelectQueryField.tsx
packages/web-main/src/components/selects/RoleSelectQueryField.tsx
packages/web-main/src/components/selects/TimePeriodSelectField.tsx
packages/web-main/src/routes/_auth/_global/user.$userId.role.assign.tsx
packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/-ShopListingCreateUpdateForm.tsx
packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.import.gameserver.tsx

This should improve select fields sizing

bugfix: always render select in portal

---

packages/lib-components/src/components/actions/ToggleButton/ToggleButtonGroup.tsx
packages/web-main/src/components/JsonSchemaForm/templates/ObjectFieldTemplate.tsx
packages/web-main/src/queries/module.tsx
packages/web-main/src/routes/_auth/-module-builder/ModuleOnboarding.tsx
packages/web-main/src/routes/_auth/_global/-roles/RoleCreateUpdateForm.tsx

Some cards were missing a card body resulting in incorrect styling

Fix: cards without body

---

package-lock.json
packages/web-main/src/routes/_auth/_global/-roles/RolesTableView.tsx

it used the current pagination total instead of the actual total

bugfix(web-main): players/users with role showing incorrect amount

---

packages/web-main/src/components/selects/GameServerSelectQueryField/index.tsx

Fixes the issue where this select crashes or returns empty

fix role assign server select

---

package.json

All other unit tests get run with native node test runner

Only run required frontend tests

---

package-lock.json
package.json
packages/app-api/src/controllers/BanController.ts
packages/app-api/src/controllers/CommandController.ts
packages/app-api/src/controllers/CronJobController.ts
packages/app-api/src/controllers/DiscordController.ts
packages/app-api/src/controllers/DomainController.ts
packages/app-api/src/controllers/EventController.ts
packages/app-api/src/controllers/FunctionController.ts
packages/app-api/src/controllers/GameServerController.ts
packages/app-api/src/controllers/HookController.ts
packages/app-api/src/controllers/ItemController.ts
packages/app-api/src/controllers/Module/installations.ts
packages/app-api/src/controllers/Module/modules.ts
packages/app-api/src/controllers/Module/versions.ts
packages/app-api/src/controllers/PlayerController.ts
packages/app-api/src/controllers/PlayerOnGameserverController.ts
packages/app-api/src/controllers/Rolecontroller.ts
packages/app-api/src/controllers/Shop/Listing.ts
packages/app-api/src/controllers/Shop/Order.ts
packages/app-api/src/controllers/UserController.ts
packages/app-api/src/controllers/VariableController.ts
packages/app-api/src/controllers/shared.ts
packages/lib-http/src/controllers/meta.ts

Add example bodies to API spec

---

packages/web-docs/docs/advanced/adding-support-for-a-new-game.mdx
packages/web-docs/docs/supported-games/minecraft.md

Add comprehensive Minecraft documentation including installation, configuration, and GitHub reference. Include Minecraft mod as reference implementation for generic connector.

Add Minecraft support documentation

---

packages/app-mock-gameserver/src/bin.ts

- Implement exponential backoff retry mechanism when connector service is unavailable
- Replace uncaught exception crash with graceful error handling
- Add clear warning messages for connection retry attempts
When running `docker compose up`, if the mock gameserver starts before the connector service is ready, it crashes with an uncaught ECONNREFUSED error. This creates a poor developer experience with ugly error messages.
Added retry logic with exponential backoff that:
- Retries connection up to 30 times (approximately 15 minutes)
- Starts with 5-second delay, increases up to 60 seconds
- Shows clear warning messages with attempt count
- Continues running the mock server even if connection ultimately fails
- Only retries for ECONNREFUSED errors (connection issues)
- Throws immediately …

Add graceful retry logic for mock gameserver connection
